AllCops:
  TargetRubyVersion: 2.1
  Exclude:
    - 'bin/*'
    - 'vendor/**/*'

Rails:
  Enabled: false

Naming/FileName:
  Exclude:
    - 'lib/acme-client.rb'

Lint/AssignmentInCondition:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Layout/MultilineOperationIndentation:
  Enabled: false

Style/SignalException:
  EnforcedStyle: only_raise

Layout/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Layout/ElseAlignment:
  Enabled: false

Style/MultipleComparison:
  Enabled: false

Layout/IndentationWidth:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Layout/FirstParameterIndentation:
  EnforcedStyle: consistent

Style/TrailingCommaInArguments:
  Enabled: false

Style/PercentLiteralDelimiters:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Layout/SpaceInsideBlockBraces:
  Enabled: false

Style/StringLiterals:
  Enabled: single_quotes

Metrics/LineLength:
  Max: 140

Metrics/ParameterLists:
  Max: 5
  CountKeywordArgs: false

Layout/EndAlignment:
  Enabled: false

Style/ParallelAssignment:
  Enabled: false

Style/ModuleFunction:
  Enabled: false

Style/TrivialAccessors:
  AllowPredicates: true

Lint/UnusedMethodArgument:
  AllowUnusedKeywordArguments: true

Metrics/MethodLength:
  Max: 15

Style/DoubleNegation:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/MultilineBlockChain:
  Enabled: false

Style/BlockDelimiters:
  EnforcedStyle: semantic

Style/Lambda:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/Alias:
  Enabled: false

Lint/AmbiguousOperator:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Style/MutableConstant:
  Enabled: false

Style/GlobalVars:
  Enabled: false

Style/ExpandPathArguments:
  Enabled: false

Security/JSONLoad:
  Enabled: false

Naming/AccessorMethodName:
  Enabled: false
